### ISSUE TITLE
How to change text field style / done button?

### ISSUE THREAD

**Issue by deding** [tristanhimmelman/THContactPicker#27]
First of all - awesome project!

As I was setting up my implementation of the THContactPicker - I didn't see a way to specify the keyboard style or the done button without modifying the source files.  Is there a way to do this without modification?  If not I think this would be a useful feature to add

**Comment by deding** [comment]
Oops! I see how to change the keyboard appearance now.  But still not seeing a way to specify the done button.

**Comment by tristanhimmelman** [comment]
Thanks! 

No there isn't a way to do that at the moment. If you feel up to it, it'd be great if you could add that feature and submit a pull request

**Comment by deding** [comment]
Thanks Tristan!

Pull request has been submitted.

**Comment by tristanhimmelman** [comment]
:+1: :+1:
