### ISSUE TITLE
Keyboard appears on calls to addContact 

### ISSUE THREAD

**Issue by kenleezle** [tristanhimmelman/THContactPicker#29]
This only happens after I have added enough contacts to cause the textView to start scrolling. Then it happens pretty regularly but not quite 100% of the time.

**Comment by kenleezle** [comment]
In the demo app you have provided the keyboard comes up under the same circumstances, however it then stays up never resigns, even on scroll.

**Comment by kenleezle** [comment]
It is this [THContactPickerView line 187](https://github.com/tristanhimmelman/THContactPicker/blob/master/Classes/THContactPickerView.m#L187) which is causing this. What is the case where this needs to be there?

**Comment by kenleezle** [comment]
pull request coming

**Comment by tristanhimmelman** [comment]
You're right, this is a bug. _shouldSelectTextView should only be set to true if the keyboard was open to begin with. Waiting on your PR
