### ISSUE TITLE
Is there any way to get a blinking cursor when the keyboard is raised?

### ISSUE THREAD

**Issue by kenleezle** [tristanhimmelman/THContactPicker#35]
To indicate that the text input is in focus, and where you will be typing?

**Comment by tristanhimmelman** [comment]
There is a blinking cursor. Only if you have a contact selected does the blinking cursor disappear

**Comment by kenleezle** [comment]
ahh, might be i killed it with colors. thanks for the response and i'll check it out on my end. i already fired up your demo and sure enough there is a blinking cursor there with the system default accent color (blue).

**Comment by kenleezle** [comment]
for anyone's reference, the cursor color is controlled by the tintColor.
This can be modified in the interface builder or in code by modifying the contactPickerView.tintColor
