### ISSUE TITLE
How to add "choose all" button?

### ISSUE THREAD

**Issue by invisible66** [tristanhimmelman/THContactPicker#47]
Hi, 
i want to add "choose all" action to left bar button. how can i choose all contacts?

**Comment by jguffey** [comment]
You'd have to use the `- (void)addContact:(id)contact withName:(NSString *)name;` within a loop to add all contacts to the view. Adding a "choose all" button to your bar buttons is outside the scope of this project, but you may check out [StackOverflow's answer to the question.](http://stackoverflow.com/questions/1219779/how-to-add-a-right-button-to-a-uinavigationcontroller)

**Comment by invisible66** [comment]
thanks @jguffey .
